### ISSUE TITLE
POS Module - Barcode Scanner

### ISSUE THREAD

**Issue by chhinsras** [fluentpos/fluentpos#103]
- [ ] Scanner Setting
- [ ] Product Search By Scanning Barcode

**Comment by iammukeshm** [comment]
Is this something we have to do? Scanners are just I/O Peripherals. Being a web application, we will get the barcode from it anyways as an input without making any change to our existing code. What do you mean by Scanner settings?

**Comment by chhinsras** [comment]
In VB Form. I expereiend we need some kind of connection required. Web is not required? If so, thats fine.

**Comment by iammukeshm** [comment]
Yeah @chhinsras, I too worked on a POS in VB.NET. Yes, we had to mention the port number and stuff. But that was because of the older hardware. Nowadays all the Scanners are USB Compatible and we won't have to install drivers as well. It will post the barcode as input anyways.

**Comment by chhinsras** [comment]
@iammukeshm sound great.
