### ISSUE TITLE
Sales Module - Order Taking Endpoint

### ISSUE THREAD

**Issue by iammukeshm** [fluentpos/fluentpos#136]
- [x] Prepare Sales Entity Model `Sales.Orders` , `Sales.Products`, `Sales.Customer`, `Sales.Transaction` 
- [x] Prepare Request / Response DTOs
- [x] Endpoint that can accept incoming parameters and create a New Sales Record in the DB.
- [x] Ensure Safe Transactions

Expected Parameters are : 

1. **Cart ID** - Note that we will not send all the product IDs, but only the Cart ID.
2. **Customer ID**

Using **CartID**, I need to get the list of all products (id, name, price, tax, category, brand), calculate total, taxes, and save these details to **Sales.Product**.
Using **CustomerID**, I need to get details of the customer and store them to **Sales.Customer**.
This is Bounded DB Context.

**Comment by iammukeshm** [comment]
Working on this.

**Comment by unchase** [comment]
@iammukeshm We should merge # 139 before.
So that in the new code the new style has already been applied.
