### ISSUE TITLE
I have to run this project not working

### ISSUE THREAD

**Issue by JayakumarJK** [fluentpos/fluentpos#147]
I have to run this project not working

**Comment by JayakumarJK** [comment]
your application swagger not invoked

**Comment by iammukeshm** [comment]
What's the exception you get? Did you run both the server and client project separately? DId you install PostgreSQL and configure the connection strings?

**Comment by JayakumarJK** [comment]
everything done correctly
I have startup project Bootstraper

but swagger not launching bro

**Comment by JayakumarJK** [comment]
can you share your email id i will send snapshot

**Comment by iammukeshm** [comment]
i guess we have disabled swagger auto-launch.. You need to navigate manually to /swagger on your browser to access it. Is this you question? You can also paste your screenshot here for us to see.

**Comment by JayakumarJK** [comment]
Still it is not working
