### ISSUE TITLE
UI- Table is not sorting data properly , gives error.

### ISSUE THREAD

**Issue by Asad-360** [fluentpos/fluentpos#163]
- [ ] To fix table sorting issue to work in both ascending and descending order if clicked multiple times.

**Bug Description:**
Table in brand component does not sort data properly in **asc** and **desc** order. When click on the arrow more then 2 times , material loader just keep on processing and nothing in response , also on server side gives validation exception. Similar pattern is observed in other tables also.
**Screenshots**

![fluenttableexception](https://user-images.githubusercontent.com/43516964/129771293-8d4fb6b6-790f-4ef5-9d20-e5d20d7e7558.PNG)
![fluent2](https://user-images.githubusercontent.com/43516964/129771580-14b591ac-e21f-4586-97b4-f1bbddf406f5.PNG)

**Comment by iammukeshm** [comment]
added a fix at the component level. Please pull the latest, retest, and let me know if it's fine now. Thanks
