### ISSUE TITLE
Input string was not in a correct format.

### ISSUE THREAD

**Issue by Weshahi** [fluentpos/fluentpos#164]
**Describe the bug**
Input string was not in a correct format (Tax) field

**To Reproduce**
1. Login as 'Super Admin'
2. Go to 'Products'
3. Select any product to Edit
4. Click on 'Edit'
5. See error

**Expected behavior**
System should save correctly 

**Additional context**
Tax in Product Model in Catalog context is decimal while in UpdateProductCommand and RegisterProductCommand string, 
the value sent from front end is "YES" or "No" as attachment demonstrate 

![image](https://user-images.githubusercontent.com/38915673/129805218-49c9423d-8c04-43e2-8f77-ea1c0453f8e7.png)

**Comment by iammukeshm** [comment]
Fixed, please pull the latest and check again.
