### ISSUE TITLE
Tax Master - Catalog Module

### ISSUE THREAD

**Issue by iammukeshm** [fluentpos/fluentpos#165]
Current implementation - We can enter in Tax value for each product. 

We need a centralized Tax Store, where we can define different Tax values.

For ex.

Catalog.Taxes table will have the following schema
1. ID
2. TaxCode
3. Percentage
4. Description

We need CRUD for this.

This Tax Entity will be mapped to Product entity, where-in admins can assign a tax selection to products. we would need a dropdown from TaxPercentage Selection in Product Form UI.

**Comment by iammukeshm** [comment]
Descoped

**Comment by chhinsras** [comment]
why? pre-defined selection option key value pair better?
