### ISSUE TITLE
Algorithm to Generate Sales Reference Number - Sales Module

### ISSUE THREAD

**Issue by iammukeshm** [fluentpos/fluentpos#170]
Generate a more readable Sales Reference Number.
Something like S-0821-00001

**Comment by iammukeshm** [comment]
![image](https://user-images.githubusercontent.com/31455818/129956794-d162f2e1-f6e2-40ac-98b5-21e7cbb2dd70.png)

**Comment by klevisndoka** [comment]
Hello @iammukeshm 

Based on the experience I've had with POS, I think that adding Terminal (Cash Desk) and maybe also the Operator in the Reference Number will decrease the possibility of errors with duplicated or wrong reference numbers in some cases.

Let's say we have two two terminals (PC, SmartPhone) making Orders in the same time...
If they both call the method **TrackAsync** (_EntityReferenceService_) in the same time for the first order...
Probably they will both go to section below and two records will be added in entity.

`
record = new EntityReference(entityName);
_context.EntityReferences.Add(record);
referenceNumber = GenerateReferenceNumber(entityName, record.Count, monthYearString);
`

In case this is not the first order, than it will generate the same Reference for both terminals.

Maybe you are thinking FluentPos to be run by a single terminal, but if you think it can be run > 1 terminals simultaneously, lets say PC and Smartphone... this change will avoid many problems. 

Another suggestion I would have is to make **ReferenceNumber** in **Order** entity **Unique**. 
It should not happen that two Orders have the same reference.

CC: @unchase @chhinsras

**Comment by iammukeshm** [comment]
Hi @klevisndoka 

Yes, fluentpos will run on more than 1 terminal for sure. I had this in mind. We will probably add in this later, maybe with a part of the userID instead. And yeah, will make the reference column unique. Thanks for the suggestion.
