### ISSUE TITLE
Error switching to MsSql creating the Migration 

### ISSUE THREAD

**Issue by rlgordey** [fluentpos/fluentpos#175]
```json
"PersistenceSettings": {
    "UseMsSql": true,
    "UsePostgres": false,
    "connectionStrings": {
      "mssql": "Data Source=.;Initial Catalog=fluentpos;Integrated Security=True;MultipleActiveResultSets=True",
      "postgres": "Host=localhost;Database=fluentpos;Username=postgres;Password=root;Include Error Detail=true"
    }
```

d:\Projects\fluentpos\src\server\Modules\Catalog\Modules.Catalog.Infrastructure>dotnet ef migrations add "initial" --startup-project ../../../API -o Persistence/Migrations/ --context CatalogDbContext
Build started...
Build succeeded.
fail: Microsoft.EntityFrameworkCore.Database.Command[20102]
      Failed executing DbCommand (10ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      CREATE TABLE [Identity].[Roles] (
          [Id] text NOT NULL,
          [Description] text NULL,
          [Name] character varying(256) NULL,
          [NormalizedName] character varying(256) NULL,
          [ConcurrencyStamp] text NULL,
          CONSTRAINT [PK_Roles] PRIMARY KEY ([Id])
      );
An error occurred while accessing the Microsoft.Extensions.Hosting services. Continuing without the application service provider. Error: Column 'Id' in table 'Roles' is of a type that is invalid for use as a key column in an index.
Could not create constraint or index. See previous errors.
Unable to create an object of type 'CatalogDbContext'. For the different patterns supported at design time, see https://go.microsoft.com/fwlink/?linkid=851728

**Comment by Weshahi** [comment]
You can delete all migrations and run the commands again for each context. and it will be work fine in MSSQL
