### ISSUE TITLE
MS SQL still not working.

### ISSUE THREAD

**Issue by iang0ld** [fluentpos/fluentpos#179]
See image attached.

![image](https://user-images.githubusercontent.com/8695534/130343876-e870faa1-789b-4b98-be75-8307750f5614.png)

**Comment by Weshahi** [comment]
Remove all migration files and run the migration commands again to produce migrations for mssql

**Comment by iang0ld** [comment]
It now appears to be trying to run Postgress SQL again the SQL database.  Not the data types.

***@***.***
