### ISSUE TITLE
JWT Becomes null

### ISSUE THREAD

**Issue by iammukeshm** [fluentpos/fluentpos#52]
@chhinsras

**Describe the bug**
this.authService.currentUserToken$.pipe(take(1)).subscribe(token => currentUserToken = token); becomes null after login. This prevents the addition of jwt to the httpHeader

**To Reproduce**
1. Login -> Logout ->Login ->Navigate to Brands or other authorized angular pages
2. 401 Exception

I made a temporary fix by adding a check to fetch the token from local storage if in-memory jwt is null. 
This is my commit - https://github.com/fluentpos/fluentpos/commit/d95b8ebe397e93090956bc0b7579d59a32023ada

Do check it and let me know what the issue was?
Thanks

**Comment by chhinsras** [comment]
is it fixed? I still can produce error. lets me check

**Comment by klevisndoka** [comment]
I think it is fixed now with PR #54.
The problem was in the change I made in commit 27df49f2d9169a49ebdf2898f0024fa2db1a48b1
I provided services in SharedModule while they should be provided in AppliactionModule.
