### ISSUE TITLE
What was the reason for using Angular 12?

### ISSUE THREAD

**Issue by iang0ld** [fluentpos/fluentpos#56]
What was the reason for using Angular 12 instead of using Blazor Hero as your foundations?

**Comment by iammukeshm** [comment]
For me,
1. I wanted to explore new tech. Angular was on my bucket list for a long time now.
2. Build a more detached solution.

But yes, Blazor will be definitely used in this project for maybe like an 'Order Taking' Lightweight application.

@chhinsras @unchase any comments ;)

**Comment by iang0ld** [comment]
Makes sense. Thanks

**Comment by iammukeshm** [comment]
Have you gone through the fluentpos project? Any initial feedback or suggestion? @iang0ld

**Comment by iang0ld** [comment]
Not yet. Looks very good on initial viewing. I'll be going through it this week. I'll provide any feedback then.

**Comment by chhinsras** [comment]
@iang0ld we were initially picking the Blazor as client project. However, in the end, we decided to go for the Angular for some reasons:
1. The dll size for Blazor WASM is not pleasant experience for now.  Hopefully, .NET 6 will be much improvement on this. 
2. The tooling for Blazor is good but still not mature yet. 
2. Angular is, no doubt, one of the dominant the front end tech as well as the mature of the framework. 
3. The download file size is much light and also Angular supports Typescript and DI out of the box (we love that).

As @iammukeshm mentioned, we are going to work on specific module for Blazor, for sure. Possibly, the .NET MAUI will be taking part as well.

**Comment by unchase** [comment]
@iammukeshm I agree that Blazor is not mature enough yet, but my hopes are in .NET 6.
In any case, choosing a frontend framework is not the most important thing. The main thing is functionality, convenience and extensibility of the project.
