### ISSUE TITLE
Fluent POS - Roadmap

### ISSUE THREAD

**Issue by SauceCode84** [fluentpos/fluentpos#57]
I've been looking at your project this past week and am very excited to see where it is going and what you have planned for the future as it progresses.

Your choice of technologies is right up my alley, as I am familiar with both .NET ASP APIs and Angular, and I would love to contribute if and where I can. The architecture is looking promising towards a modular approach for extensibility on both the API as well as the frontend.

Do you perhaps a roadmap of some kind, i.e. what features are you are currently working on, looking at working on next and what you have planned for the future? Perhaps making use of the **[Projects](https://github.com/fluentpos/fluentpos/projects)** feature here on your project's Github, in order to organised could offer a start.

Let me know your thoughts!

**Comment by iammukeshm** [comment]
Thanks for the suggestion. Will surely come up with a roadmap in a week or so 👍
