### ISSUE TITLE
Extended Attributes

### ISSUE THREAD

**Issue by iang0ld** [fluentpos/fluentpos#63]
I am getting a little confused about the Extended Attributes.  Are you able to provide a explanation?

**Comment by unchase** [comment]
Hi, @iang0ld 

In essence, extended attributes are a key-value set, extended with auxiliary data (description, group, etc.), where the value can be stored for certain types in separate columns.

* For each entity, a separate table is created in the database with extended attributes.
* You can add an extended attribute to a specific entity; for this, in the request, we pass its identifier in the `EntityId` property.
* An extended attribute must have its value type. Depending on this type, we store the value of the extended attribute in a specific column (*decimal*, *text*, *datetime* etc.).
* In this case, all other columns (not for the selected type) in which the values of the extended attribute are stored must be null.
* The `Group` property is used to group extended attributes. For example, if the added extended attributes are security related, then we can set the `Group` property to "Security".
* The `IsActive` property can be used in scenarios when we use some extended attributes in business processes, but we want to temporarily exclude some of them from processing.
* The `ExternalId` property can be used to relate with an extended attribute externally.
* And the `Key` property of an extended attribute must be unique within the same entity.

**Comment by iang0ld** [comment]
Thank you.
