### ISSUE TITLE
Can't do initial migration

### ISSUE THREAD

**Issue by iang0ld** [fluentpos/fluentpos#66]
![image](https://user-images.githubusercontent.com/8695534/126602600-e1c390fa-0ae8-401b-a82a-8fd0a3e0476a.png)

This is the connection string I have been using successfully for a variety of projects.

![image](https://user-images.githubusercontent.com/8695534/126602688-e8ed73e7-0494-4512-b0e4-08adb79d5979.png)

**Comment by iammukeshm** [comment]
Did you remove all the existing migrations? By default, these are the migrations meant for Postgres which includes keywords like without.

**Comment by iammukeshm** [comment]
https://github.com/fluentpos/fluentpos/blob/master/docs/api-switching-database-provider-tutorial.md

This should help.

**Comment by iang0ld** [comment]
Sorry. I thought you only had to do that if you were migrating existing database. Thanks.

FYI. Very exciting.

**Comment by iammukeshm** [comment]
I would recommend sticking on to Postgres though. We have not gotten enough time to test with mssql. However, there should not be any issues as such.

**Comment by iang0ld** [comment]
I am looking to your are an exising app at used mssql so I'm happy to try.


-------- Original message --------
From: Mukesh Murugan ***@***.***>
Date: 22/7/21 5:41 pm (GMT+10:00)
To: fluentpos/fluentpos ***@***.***>
Cc: Ian Gold ***@***.***>, State change ***@***.***>
Subject: Re: [fluentpos/fluentpos] Can't do initial migration (#66)


I would recommend sticking on to Postgres though. We have not gotten enough time to test with mssql. However, there should not be any issues as such.

**Comment by iang0ld** [comment]
Not having much luck

***@***.***D77F2E.EF99DBA0]
